# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6086452db82dc0adabe886c1e22fc59aaecb7c80530d09d3c51fa23a0d912a55c8a0702061327e47f874189b741f30e980f8b9f8d211a7515b60c421f6ec6f00

test:
  secret_key_base: 279fadc5d7565c38b725c4608d6f6d87cc5aa2b5a94240c4bf8d532ea46b92e06deae543570193e42c2581a6c51abe03ad6a51e6bef482b397f45844c4d49066

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
